services:
  app:
    container_name: resmngapp-api
    build: .
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env

  db:
    container_name: resmngapp-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: ${DB_CONNECTION_USERNAME}
      MYSQL_PASSWORD: ${DB_CONNECTION_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_CONNECTION_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_CONNECTION_DATABASE}
    ports:
      - '3308:3306'
    volumes:
      - resmngapp_db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "mysql -u${DB_CONNECTION_USERNAME} -p${DB_CONNECTION_PASSWORD} -e'USE ${DB_CONNECTION_DATABASE}'",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
      start_interval: 5s

volumes:
  resmngapp_db_data:
