services:
  app:
    container_name: resmngapp-api
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env

  db:
    container_name: resmngapp-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: ${DB_CONNECTION_USERNAME}
      MYSQL_PASSWORD: ${DB_CONNECTION_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_CONNECTION_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_CONNECTION_DATABASE}
    ports:
      - '3308:3306'
    volumes:
      - resmngapp_db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  resmngapp_db_data:
